### ISSUE TITLE
Add methods for adding multiple specs at once to a FileSpecBuilder

### ISSUE THREAD

**Issue by michaelboyles** [outfoxx/typescriptpoet#22]
JavaPoet's API has methods like [addMethod**s**](https://square.github.io/javapoet/1.x/javapoet/com/squareup/javapoet/TypeSpec.Builder.html#addMethods-java.lang.Iterable-) (plural) which accept collections, in addition to the singular versions for adding one at a time.

TypescriptPoet doesn't have those.

I find it breaks the otherwise fluent API, forcing me to write things like this:

```java
fileSpecBuilder
    .addFunction(someFunction())
    .addFunction(someOtherFunction());
for (FunctionSpec spec : listOfFunctions()) {
    fileSpecBuilder.addFunction(spec);
}
```

I think it would be nicer to match JavaPoet's API by adding these plural methods:

- `addFunctions(Iterable<FunctionSpec>)`
- `addTypes(Iterable<TypeSpec<?, ?>)`
- `addClasses(Iterable<ClassSpec>)`
- `addEnums(Iterable<EnumSpec>)`
- `addInterfaces(Iterable<InterfaceSpec>)`
- `addModules(Iterable<ModuleSpec>)`
- `addProperties(Iterable<PropertySpec>)`
- `addTypeAliases(Iterable<TypeAliasSpec>)`

The downside, I suppose, is that it will bloat the API with additional methods. The workaround is to use extension methods, which I'm currently doing.

Happy to contribute a PR to implement this, if you agree it would be an improvement.

**Comment by kdubb** [comment]
Sorry about the late reply I seem to be missing some GitHub notifications. A PR is most welcome if you can!
